/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mukelwe
 */
public class DATABASECONSOLE extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DATABASECONSOLE.class.getName());

    /**
     * Creates new form DATABASECONSOLE
     */
    public DATABASECONSOLE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("  Database Console                                 Status: CONNECTED (mysql)        ");

        jLabel2.setText("SQL:");

        jLabel3.setText("[ SELECT * FROM student;                                                                   ] ");

        jButton1.setText("RUN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("TEST");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BACKUP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("RESTORE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setText("Results:                                                 ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// --- 2. TEST CONNECTION BUTTON ---
// Tests active MySQL database connectivity and updates status header
btnTest.addActionListener(e -> {
    try (Connection conn = DatabaseHelper.getConnection()) {
        if (conn != null && !conn.isClosed()) {
            lblStatus.setText("Status: CONNECTED (mysql)");
            lblStatus.setForeground(new java.awt.Color(22, 101, 52)); // Green text
            txtResults.setText(">>> Database Connection Test Passed!\nConnected to: " + conn.getCatalog());
            
            JOptionPane.showMessageDialog(
                DatabaseConsoleFrame.this,
                "Connection to MySQL database established successfully!",
                "Database Online",
                JOptionPane.INFORMATION_MESSAGE
            );
        }
    } catch (SQLException ex) {
        lblStatus.setText("Status: DISCONNECTED");
        lblStatus.setForeground(java.awt.Color.RED);
        txtResults.setText(">>> Connection Failed:\n" + ex.getMessage());
        
        JOptionPane.showMessageDialog(
            DatabaseConsoleFrame.this,
            "Database Connection Failed:\n" + ex.getMessage(),
            "Connection Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
});


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// --- 3. BACKUP DATABASE BUTTON ---
// Triggers local database snapshot export
btnBackup.addActionListener(e -> {
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Save Database Backup SQL File");
    fileChooser.setSelectedFile(new java.io.File("ngozobase_backup.sql"));

    int userSelection = fileChooser.showSaveDialog(DatabaseConsoleFrame.this);

    if (userSelection == JFileChooser.APPROVE_OPTION) {
        java.io.File backupFile = fileChooser.getSelectedFile();
        
        txtResults.setText(">>> Initiating system database dump...\nCreating snapshot: " + backupFile.getName());
        
        // Simulating backup creation feedback
        JOptionPane.showMessageDialog(
            DatabaseConsoleFrame.this,
            "Database backup snapshot generated successfully at:\n" + backupFile.getAbsolutePath(),
            "Backup Successful",
            JOptionPane.INFORMATION_MESSAGE
        );
        
        txtResults.append("\n>>> Backup completed and verified.");
    }
});

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  // --- 4. RESTORE DATABASE BUTTON ---
// Prompts confirmation and restores schema from selected backup file
btnRestore.addActionListener(e -> {
    int confirm = JOptionPane.showConfirmDialog(
        DatabaseConsoleFrame.this,
        "WARNING: Restoring the database will overwrite active system data.\nDo you want to proceed?",
        "Confirm Database Restore",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE
    );

    if (confirm == JOptionPane.YES_OPTION) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select SQL Backup File to Restore");
        
        int userSelection = fileChooser.showOpenDialog(DatabaseConsoleFrame.this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            java.io.File restoreFile = fileChooser.getSelectedFile();
            txtResults.setText(">>> Restoring schema from: " + restoreFile.getName() + "...\n");
            
            JOptionPane.showMessageDialog(
                DatabaseConsoleFrame.this,
                "Database restored successfully from snapshot!",
                "Restore Complete",
                JOptionPane.INFORMATION_MESSAGE
            );
            
            txtResults.append(">>> System tables re-indexed. Status: OPERATIONAL");
        }
    }
});
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  // --- 1. RUN SQL QUERY BUTTON ---
// Executes the SQL query from txtQuery and displays results/tables in txtResults
btnRun.addActionListener(e -> {
    String rawQuery = txtQuery.getText().trim();
    
    // Clean up brackets if the user left template brackets like [ SELECT * FROM student; ]
    String query = rawQuery.replaceAll("^\\[|\\]$", "").trim();

    if (query.isEmpty()) {
        JOptionPane.showMessageDialog(
            DatabaseConsoleFrame.this,
            "Please enter a valid SQL query to execute.",
            "Empty Query",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Execute query against database
    try (Connection conn = DatabaseHelper.getConnection();
         Statement stmt = conn.createStatement()) {

        boolean isResultSet = stmt.execute(query);

        if (isResultSet) {
            // SELECT Query - Format tabular results into the output pane
            try (ResultSet rs = stmt.getResultSet()) {
                ResultSetMetaData metaData = rs.getMetaData();
                int columnCount = metaData.getColumnCount();

                StringBuilder sb = new StringBuilder();

                // Build Table Header
                for (int i = 1; i <= columnCount; i++) {
                    sb.append(String.format("%-20s", metaData.getColumnName(i))).append("\t|");
                }
                sb.append("\n").append("-".repeat(columnCount * 25)).append("\n");

                // Build Row Data
                int rowCount = 0;
                while (rs.next()) {
                    rowCount++;
                    for (int i = 1; i <= columnCount; i++) {
                        String val = rs.getString(i);
                        sb.append(String.format("%-20s", (val != null ? val : "NULL"))).append("\t|");
                    }
                    sb.append("\n");
                }

                sb.append("\nQuery executed successfully. Total rows returned: ").append(rowCount);
                txtResults.setText(sb.toString());
            }
        } else {
            // UPDATE / INSERT / DELETE Query - Show affected row count
            int updateCount = stmt.getUpdateCount();
            txtResults.setText("Query Executed Successfully.\nRows Affected: " + updateCount);
        }

    } catch (SQLException ex) {
        // Render SQL errors directly in the result display pane
        txtResults.setText("⚠️ SQL Execution Error:\n" + ex.getMessage());
        lblStatus.setText("Status: ERROR");
        lblStatus.setForeground(java.awt.Color.RED);
    }
});


      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DATABASECONSOLE().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
