/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Mukelwe
 */
public class TeacherDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TeacherDashboard.class.getName());

    /**
     * Creates new form TeacherDashboard
     */
    public TeacherDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlNavigation = new javax.swing.JPanel();
        btnUploadAssignment = new javax.swing.JButton();
        btnUploadMarkd = new javax.swing.JButton();
        btnSetTestDate = new javax.swing.JButton();
        btnAddComment = new javax.swing.JButton();
        btnSendMessage = new javax.swing.JButton();
        Messages = new javax.swing.JTabbedPane();
        tpnlContent = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblStatusBar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        mbTeacher = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuItemUpLeadAssignment = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ngozobase-TeacherDashboard");
        setBackground(new java.awt.Color(102, 102, 0));
        setForeground(new java.awt.Color(102, 102, 0));

        pnlNavigation.setBackground(new java.awt.Color(0, 153, 153));
        pnlNavigation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        btnUploadAssignment.setText("Upload Assignment");
        btnUploadAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadAssignmentActionPerformed(evt);
            }
        });

        btnUploadMarkd.setText("Upload Marks");
        btnUploadMarkd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadMarkdActionPerformed(evt);
            }
        });

        btnSetTestDate.setText("Set Test Date");
        btnSetTestDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetTestDateActionPerformed(evt);
            }
        });

        btnAddComment.setText("Add Comment");
        btnAddComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCommentActionPerformed(evt);
            }
        });

        btnSendMessage.setText("Send Message");
        btnSendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNavigationLayout = new javax.swing.GroupLayout(pnlNavigation);
        pnlNavigation.setLayout(pnlNavigationLayout);
        pnlNavigationLayout.setHorizontalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUploadAssignment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUploadMarkd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSetTestDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddComment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSendMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavigationLayout.setVerticalGroup(
            pnlNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavigationLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnUploadAssignment)
                .addGap(18, 18, 18)
                .addComponent(btnUploadMarkd)
                .addGap(18, 18, 18)
                .addComponent(btnSetTestDate)
                .addGap(18, 18, 18)
                .addComponent(btnAddComment)
                .addGap(18, 18, 18)
                .addComponent(btnSendMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Messages.setBackground(new java.awt.Color(0, 153, 153));

        tpnlContent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Messages.addTab("My Classes", tpnlContent);

        jLabel2.setText("jLabel2");
        Messages.addTab("Messages", jLabel2);

        lblStatusBar.setText("Role : Subject Teacher");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jMenu1.setText("File");
        mbTeacher.add(jMenu1);

        jMenu2.setText("Academics");

        menuItemUpLeadAssignment.setText("upload Assignment");
        menuItemUpLeadAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUpLeadAssignmentActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemUpLeadAssignment);

        mbTeacher.add(jMenu2);

        jMenu3.setText("Communication ");
        mbTeacher.add(jMenu3);

        jMenu4.setText("Help");
        mbTeacher.add(jMenu4);

        setJMenuBar(mbTeacher);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Messages))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(lblStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Messages, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatusBar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemUpLeadAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUpLeadAssignmentActionPerformed
       // Opens the Upload Assignment dialog when clicked from the menu
    UploadAssignmentDialog dialog = new UploadAssignmentDialog(this, true);
    dialog.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_menuItemUpLeadAssignmentActionPerformed

    private void btnUploadAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadAssignmentActionPerformed
     // Opens the Upload Assignment Dialog (Modal)
  //  UploadAssignmentDialog dialog = new UploadAssignmentDialog(this, true);
  //  dialog.setVisible(true);   // TODO add your handling code here:
    
    	// --- 1. UPLOAD ASSIGNMENT BUTTON ---
	// Opens a file picker so teachers can upload class documents or homework files
	btnUploadAssignment.addActionListener(e -> {
	    JFileChooser fileChooser = new JFileChooser();
	    fileChooser.setDialogTitle("Select Assignment File to Upload");
	    	    int userSelection = fileChooser.showOpenDialog(TeacherHomeFrame.this);
	    if (userSelection == JFileChooser.APPROVE_OPTION) {
	        String fileName = fileChooser.getSelectedFile().getName();
	        JOptionPane.showMessageDialog(
	            TeacherHomeFrame.this,
	            "Successfully uploaded: " + fileName + "\nAssigned to active class.",
	            "Upload Complete",
	            JOptionPane.INFORMATION_MESSAGE
	        );
	    }
	});

    }//GEN-LAST:event_btnUploadAssignmentActionPerformed

    private void btnUploadMarkdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadMarkdActionPerformed
// Opens the Upload Assignment Dialog (Modal)
    //UploadAssignmentDialog dialog = new UploadAssignmentDialog(this, true);
  //  dialog.setVisible(true);        // TODO add your handling code here:
	// --- 2. UPLOAD MARKS BUTTON ---
	// Opens the dedicated UploadMarksFrame gradebook window
	btnUploadMarks.addActionListener(e -> {
	    UploadMarksFrame marksFrame = new UploadMarksFrame();
	    marksFrame.setVisible(true);
	});
	
 
    
    }//GEN-LAST:event_btnUploadMarkdActionPerformed

    private void btnSendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMessageActionPerformed
      // Opens the Messages Window
    new MessagesWindow().setVisible(true);  // TODO add your handling code here:
    	// --- 5. SEND MESSAGE BUTTON ---
	// Opens the MessageWindowFrame communication portal
	btnSendMessage.addActionListener(e -> {
	    MessageWindowFrame messageFrame = new MessageWindowFrame();
	    messageFrame.setVisible(true);
	});

    }//GEN-LAST:event_btnSendMessageActionPerformed

    private void btnSetTestDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetTestDateActionPerformed
        // TODO add your handling code here:
        	// --- 3. SET TEST DATE BUTTON ---
	// Opens the shared calendar interface to schedule upcoming assessments
	btnSetTestDate.addActionListener(e -> {
	    SharedCalendarFrame calendarFrame = new SharedCalendarFrame();
	    calendarFrame.setVisible(true);
	});

    }//GEN-LAST:event_btnSetTestDateActionPerformed

    private void btnAddCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCommentActionPerformed
        // TODO add your handling code here:
        	// --- 4. ADD COMMENT BUTTON ---
	// Prompts the teacher to enter a quick academic progress note for a student
	btnAddComment.addActionListener(e -> {
	    String studentName = JOptionPane.showInputDialog(
	        TeacherHomeFrame.this,
	        "Enter Student Name or ID:",
	        "Add Academic Comment",
	        JOptionPane.QUESTION_MESSAGE
	    );
	
	    if (studentName != null && !studentName.trim().isEmpty()) {
	        String comment = JOptionPane.showInputDialog(
	            TeacherHomeFrame.this,
	            "Enter academic remark for " + studentName + ":",
	            "Teacher Feedback",
	            JOptionPane.PLAIN_MESSAGE
	        );
	
	        if (comment != null && !comment.trim().isEmpty()) {
	            JOptionPane.showMessageDialog(
	                TeacherHomeFrame.this,
	                "Comment saved to " + studentName + "'s profile!",
	                "Success",
	                JOptionPane.INFORMATION_MESSAGE
	            );
	        }
	    }
	});

    }//GEN-LAST:event_btnAddCommentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TeacherDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Messages;
    private javax.swing.JButton btnAddComment;
    private javax.swing.JButton btnSendMessage;
    private javax.swing.JButton btnSetTestDate;
    private javax.swing.JButton btnUploadAssignment;
    private javax.swing.JButton btnUploadMarkd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatusBar;
    private javax.swing.JMenuBar mbTeacher;
    private javax.swing.JMenuItem menuItemUpLeadAssignment;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JLabel tpnlContent;
    // End of variables declaration//GEN-END:variables
}
